brain_to_wave:
  id:
    0: 1
    1: 43
    10: 55
    20: 67
    2: 2
    3: 3
    4: 4
    5: 5
    6: 6
    7: 7
    8: 8
    9: 9
    11: 11
    12: 12
    13: 13
    14: 14
    15: 15
    16: 16
    17: 17
    18: 18
    19: 19
    21: 21
    22: 22
    23: 23
    24: 24
    25: 25
    26: 26
    27: 27
    28: 28
    29: 29
    30: 30
    31: 31
    32: 32
    33: 33
    34: 34
    35: 35
    36: 36
    37: 37
    38: 38
    39: 39
    40: 40
    41: 41
    42: 42
    43: 43
    44: 44
    45: 45
    46: 46
    47: 47
    48: 48
    49: 49
    50: 50
    51: 51
    52: 52
    53: 53
    54: 54
    55: 55
    56: 56
    57: 57
    58: 58
    59: 59
    60: 60
    61: 61
    62: 62
    63: 63
    64: 64
    65: 65
    66: 66
    67: 67
    68: 68
    69: 69
    70: 70
    71: 71
    72: 72
    73: 73
    74: 74
    75: 75
    76: 76
    77: 77
    78: 78
    79: 79
    80: 80
    81: 81
    82: 82
    83: 83
    84: 84
    85: 85
    86: 86
    87: 87
    88: 88
    89: 89
    90: 90



  population:
    1: 48
    2: 48
    3: 48
    4: 48
    5: 48
    6: 48
    7: 48
    8: 48
    9: 48
    10: 48
    11: 48
    12: 48
    13: 48
    14: 48
    15: 48
    16: 48
    17: 51
    18: 51
    19: 51
    20: 51
    21: 51
    22: 51
    23: 51
    24: 51
    25: 51
    26: 51
    27: 51
    28: 51
    29: 51
    30: 51
    31: 51
    32: 51
    33: 53
    34: 53
    35: 53
    36: 53
    37: 53
    38: 53
    39: 53
    40: 53
    41: 53
    42: 53
    43: 53
    44: 53
    45: 53
    46: 53
    47: 53
    48: 53
    49: 55
    50: 55
    51: 55
    52: 55
    53: 55
    54: 55
    55: 55
    56: 55
    57: 55
    58: 55
    59: 55
    60: 55
    61: 55
    62: 55
    63: 55
    64: 55
    65: 58
    66: 58
    67: 58
    68: 58
    69: 58
    70: 58
    71: 58
    72: 58
    73: 58
    74: 58
    75: 58
    76: 58
    77: 58
    78: 58
    79: 58
    80: 58
    81: 58
